config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/create'

  get 'sessions/destroy'
                             
  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products

  resources :products do
    get :who_bought, on: :member
  end

  root to: 'store#index', as: 'store'

  resources :line_items do
    put 'decrement', on: :member
  end
  resources :line_items do
    put 'increment', on: :member
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Ruby test</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body class="<%= controller.controller_name %>">
		<div id="banner">
			<%= image_tag("ruby.jpg") %>
			<%= @page_title || "Тестовый магазин" %>
		</div>
		<div id="columns">
			<div id="side">
			<% if @cart %>
				<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
					<%= render @cart %>
				<% end %>
			<% end %>
				<ul>
					<li><a href="/">Главная</a></li>
					<li><a href="/faq">Вопросы</a></li>
					<li><a href="/news">Новости</a></li>
					<li><a href="/contact">Контакты</a></li>
					<% unless session[:user_id] %>
					<li><%= link_to "Вход", login_path %></li>
					<% end %>
				</ul>

				<% if session[:user_id] %>
					<ul>
						<li><%= link_to "Заказы", orders_path %></li>
						<li><%= link_to "Товары", products_path %></li>
						<li><%= link_to "Пользователи", users_path %></li>
					</ul>
					<%= button_to 'Выйти', logout_path, method: :delete %>
				<% end %>

			</div>
			<div id="main">
				<%= yield %>
			</div>
		</div>
	</body>
</html>